Add SharedPreferenceExt.kt and its unitTest
mobillium/KlobalX pull request #3
Opened 2023-05-12 12:06 UTC by ebayraktar

2023-05-12 14:15 UTC, samideliceli requested changes

2023-05-12 14:15 UTC, samideliceli commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/SharedPreferenceExt.kt
> +inline fun SharedPreferences.put(func: SharedPreferences.Editor.() -> Unit) {
kaldırabiliriz

2023-05-12 14:15 UTC, samideliceli commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/SharedPreferenceExt.kt
> +fun SharedPreferences.put(vararg pairs: Pair<String, Any>) {
set yapabiliriz fun'ı

2023-06-02 12:38 UTC, nezih94 approved these changes

2023-06-02 13:01 UTC, akndmr approved these changes
Eline sağlık!

2023-06-02 13:02 UTC, samideliceli approved these changes

2023-06-02 13:03 UTC, aliosmanay approved these changes

2023-06-02 13:03 UTC, merged