Add keyboard, context extensions
mobillium/KlobalX pull request #4
Opened 2023-05-12 12:07 UTC by Muratoter

2023-05-12 12:20 UTC, nezih94 reviewed
Selam Murat. **androidx.core** destek paketinde klavye ile ilgili işlemler için daha yeni ve **farklı android versiyonlarında daha tutarlı olan** fonksiyonlar var. Bunları kullanmamız daha doğru olur.

Bu fonksiyonları anlatan örnek bir [makale](https://jeremyleenz.medium.com/how-to-show-hide-the-onscreen-keyboard-in-android-42ebedc6f430)

2023-05-12 13:55 UTC, samideliceli requested changes

2023-05-12 13:55 UTC, samideliceli commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/KeyboardExt.kt
> +    val inputMethodManager = context?.getSystemService(Activity.INPUT_METHOD_SERVICE) as InputMethodManager
requiredActivity?.hideKeyboard() şeklinde kısaltabiliriz

2023-06-02 12:36 UTC, nezih94 approved these changes

2023-06-02 13:10 UTC, akndmr requested changes

2023-06-02 13:10 UTC, akndmr commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/KeyboardExt.kt
> +fun Fragment.showKeyboard() = activity?.showKeyboard()
requireActivity()

2023-06-02 13:15 UTC, ebayraktar approved these changes

2023-06-02 13:37 UTC, akndmr approved these changes
Eline sağlık!

2023-06-02 13:40 UTC, samideliceli approved these changes

2023-06-02 13:41 UTC, merged