Add view height, width extensions
mobillium/KlobalX pull request #5
Opened 2023-05-12 12:34 UTC by kerimisoffline

2023-05-12 13:46 UTC, samideliceli requested changes

2023-05-12 13:46 UTC, samideliceli commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/ViewExt.kt
> +    val layoutParams = this.layoutParams
değişken ismi değiştirilip thisler kaldırılabilir.

2023-05-12 13:46 UTC, samideliceli commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/ViewExt.kt
> +    val layoutParams = this.layoutParams
scope alınabilir

2023-05-12 13:46 UTC, samideliceli commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/ViewExt.kt
>      this.visibility = View.INVISIBLE
thisler kalkabilir

2023-06-02 09:24 UTC, ckavuzlu approved these changes

2023-06-02 13:14 UTC, akndmr approved these changes
Eline sağlık!

2023-06-02 13:15 UTC, samideliceli approved these changes

2023-06-02 13:15 UTC, ebayraktar approved these changes

2023-06-02 13:15 UTC, ebayraktar approved these changes

2023-06-02 13:15 UTC, merged