Add extensions
mobillium/KlobalX pull request #6
Opened 2023-05-12 12:36 UTC by akndmr

2023-05-12 13:38 UTC, samideliceli requested changes

2023-05-12 13:38 UTC, samideliceli commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/ActivityExt.kt
> +        Uri.fromParts("package", packageName, null)
package consta alınabilir

2023-05-12 13:38 UTC, samideliceli commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/ActivityExt.kt
> +    val intent = Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS)
scope ile kısaıltılabilir

2023-06-02 09:22 UTC, ckavuzlu approved these changes

2023-06-02 13:17 UTC, samideliceli approved these changes

2023-06-02 13:18 UTC, nezih94 approved these changes

2023-06-02 13:19 UTC, merged