Add snackbar extention for fragments
mobillium/KlobalX pull request #7
Opened 2023-05-25 12:50 UTC by TamerSarioglu

2023-06-02 13:20 UTC, akndmr requested changes

2023-06-02 13:20 UTC, akndmr commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/FragmentExt.kt
> +    activity?.let { Snackbar.make(it.findViewById(android.R.id.content), snackBarText, timeLength).show() }
requireActivity()

2023-06-02 13:20 UTC, akndmr commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/FragmentExt.kt
> +fun Fragment.showSnackBar(snackBarText: String, timeLength: Int) {
timeLength = Default değer verebiliriz

2023-06-08 14:10 UTC, akndmr requested changes

2023-06-08 14:10 UTC, akndmr commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/FragmentExt.kt
> +fun Fragment.showSnackBar(snackBarText: String) {
Burada değişkene default Snackbar short length değerini verelim ki zorunlu değişken olmasın diye.

`fun Fragment.showSnackBar(snackBarText: String, timeLength: Int = SnackBar.LENGTH_SHORT)`

Altta 2 yerine de `timeLength`'i verebiliriz.

2023-06-08 14:23 UTC, samideliceli commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/FragmentExt.kt
> +fun Fragment.showSnackBar(snackBarText: String) {
@TamerSarioglu

2023-06-08 14:30 UTC, akndmr approved these changes
Eline sağlık!

2023-06-08 14:30 UTC, samideliceli approved these changes

2023-06-08 14:30 UTC, merged