Add Bundle, Intent, Uri Extensions
mobillium/KlobalX pull request #9
Opened 2023-05-26 11:59 UTC by ali-kosesakal

2023-06-02 09:15 UTC, ckavuzlu approved these changes

2023-06-02 13:30 UTC, akndmr requested changes
Eline sağlık, ufak değişiklikler var

2023-06-02 13:30 UTC, akndmr commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/BundleExt.kt
> +inline fun <reified T : Parcelable> Bundle.parcelable(key: String): T? = when {
Bunu silebiliriz.

2023-06-02 13:30 UTC, akndmr commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/IntentExt.kt
> +inline fun <reified T : Parcelable> Intent.parcelable(key: String): T? = when {
Bunu silebiliriz.

2023-06-02 13:30 UTC, akndmr commented on klobalx/src/main/java/com/mobillium/klobalx/nativeext/UriExt.kt
> +    if (Build.VERSION.SDK_INT >= 29) {
`runCatching` 'e alabiliriz. `getOrElse` dönebiliriz.

2023-06-08 14:23 UTC, samideliceli approved these changes

2023-06-08 14:23 UTC, akndmr approved these changes
Eline sağlık!

2023-06-08 14:24 UTC, merged